{
 "title": "eric-oss-file-notification-stub",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Time panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Files Uploaded per ROP Time ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:sftp_files_uploaded_per_rop_time{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Files Renamed per ROP Time ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:sftp_files_renamed_per_rop_time{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "File Notifications per ROP Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:kafka_notifications_per_rop_time{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Topic Specific File Notification panels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "PM Counter File Notifications sent Per ROP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:kafka_notifications_sftp_filetrans_per_rop{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Event 4G File Notifications sent Per ROP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:kafka_notifications_event4g_per_rop{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Event 5G File Notifications sent Per ROP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:kafka_notifications_event5g_per_rop{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "File Notification panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "File Notifications sent Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:kafka_notifications_total{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "File Notifications sent per ROP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:kafka_notifications_per_rop{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "File uploads/renames panels", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Files Renamed Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:sftp_files_renamed_total{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Files Renamed per ROP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:sftp_files_renamed_per_rop{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Files Uploaded Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:sftp_files_uploaded_total{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Files Uploaded per ROP",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "eric_oss_file_notification_enm_stub:sftp_files_uploaded_per_rop{app_kubernetes_io_managed_by=\"\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Test panels",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Files Uploaded per ROP (increase)",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "increase(eric_oss_file_notification_enm_stub:sftp_files_uploaded_per_rop{app_kubernetes_io_managed_by=\"\"}[15m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Files Renamed per ROP (increase)",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "increase(eric_oss_file_notification_enm_stub:sftp_files_renamed_total{app_kubernetes_io_managed_by=\"\"}[15m])",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}